
import type { LucideIcon } from 'lucide-react';
import * as LucideIcons from 'lucide-react';

// A curated map of available icons for categories
// Ensure the string keys here are consistent with iconName stored/entered.
export const availableIcons: Record<string, LucideIcon> = {
  MessageSquare: LucideIcons.MessageSquare,
  ShieldCheck: LucideIcons.ShieldCheck,
  Users: LucideIcons.Users,
  Code: LucideIcons.Code,
  HelpCircle: LucideIcons.HelpCircle,
  Briefcase: LucideIcons.Briefcase,
  LayoutList: LucideIcons.LayoutList,
  Annoyed: LucideIcons.Annoyed,
  Archive: LucideIcons.Archive,
  Award: LucideIcons.Award,
  BadgeHelp: LucideIcons.BadgeHelp,
  BarChart: LucideIcons.BarChart3, // Note: BarChart3 used in dashboard, ensure consistency if needed
  Book: LucideIcons.Book,
  Bug: LucideIcons.Bug,
  Building: LucideIcons.Building,
  Camera: LucideIcons.Camera,
  Cat: LucideIcons.Cat,
  CheckCircle2: LucideIcons.CheckCircle2,
  ChevronDownSquare: LucideIcons.ChevronDownSquare,
  ClipboardList: LucideIcons.ClipboardList,
  Cloud: LucideIcons.Cloud,
  Coffee: LucideIcons.Coffee,
  Cog: LucideIcons.Cog,
  Compass: LucideIcons.Compass,
  Database: LucideIcons.Database,
  Dog: LucideIcons.Dog,
  DollarSign: LucideIcons.DollarSign,
  Download: LucideIcons.Download,
  Edit: LucideIcons.Edit,
  ExternalLink: LucideIcons.ExternalLink,
  Feather: LucideIcons.Feather,
  FileText: LucideIcons.FileText,
  Film: LucideIcons.Film,
  Filter: LucideIcons.Filter,
  Flag: LucideIcons.Flag,
  Folder: LucideIcons.Folder,
  Gamepad2: LucideIcons.Gamepad2,
  Gift: LucideIcons.Gift,
  Globe: LucideIcons.Globe,
  Grid: LucideIcons.Grid,
  Heart: LucideIcons.Heart,
  Home: LucideIcons.Home,
  Image: LucideIcons.Image,
  Info: LucideIcons.Info,
  Key: LucideIcons.Key,
  Layers: LucideIcons.Layers,
  Lightbulb: LucideIcons.Lightbulb,
  Link: LucideIcons.Link,
  List: LucideIcons.List,
  Lock: LucideIcons.Lock,
  Mail: LucideIcons.Mail,
  MapPin: LucideIcons.MapPin,
  Menu: LucideIcons.Menu,
  Mic: LucideIcons.Mic,
  MinusSquare: LucideIcons.MinusSquare,
  Monitor: LucideIcons.Monitor,
  Moon: LucideIcons.Moon,
  Music: LucideIcons.Music,
  Navigation: LucideIcons.Navigation,
  Package: LucideIcons.Package,
  Paperclip: LucideIcons.Paperclip,
  Pencil: LucideIcons.Pencil,
  Percent: LucideIcons.Percent,
  Phone: LucideIcons.Phone,
  PieChart: LucideIcons.PieChart,
  PlayCircle: LucideIcons.PlayCircle,
  PlusSquare: LucideIcons.PlusSquare,
  Pocket: LucideIcons.Pocket,
  Power: LucideIcons.Power,
  Printer: LucideIcons.Printer,
  Radio: LucideIcons.Radio,
  RefreshCw: LucideIcons.RefreshCw,
  Save: LucideIcons.Save,
  Scissors: LucideIcons.Scissors,
  Search: LucideIcons.Search,
  Send: LucideIcons.Send,
  Settings: LucideIcons.Settings,
  Share2: LucideIcons.Share2,
  ShoppingCart: LucideIcons.ShoppingCart,
  Smile: LucideIcons.Smile,
  Speaker: LucideIcons.Speaker,
  Star: LucideIcons.Star,
  Sun: LucideIcons.Sun,
  Sunrise: LucideIcons.Sunrise,
  Sunset: LucideIcons.Sunset,
  Table: LucideIcons.Table,
  Tag: LucideIcons.Tag,
  Target: LucideIcons.Target,
  Terminal: LucideIcons.Terminal,
  ThumbsDown: LucideIcons.ThumbsDown,
  ThumbsUp: LucideIcons.ThumbsUp,
  ToggleLeft: LucideIcons.ToggleLeft,
  ToggleRight: LucideIcons.ToggleRight,
  Tool: LucideIcons.Tool,
  Trash2: LucideIcons.Trash2,
  TrendingDown: LucideIcons.TrendingDown,
  TrendingUp: LucideIcons.TrendingUp,
  Truck: LucideIcons.Truck,
  Tv: LucideIcons.Tv,
  Umbrella: LucideIcons.Umbrella,
  Upload: LucideIcons.Upload,
  Video: LucideIcons.Video,
  Volume2: LucideIcons.Volume2,
  Watch: LucideIcons.Watch,
  Wifi: LucideIcons.Wifi,
  Wind: LucideIcons.Wind,
  XSquare: LucideIcons.XSquare,
  Zap: LucideIcons.Zap,
  ZoomIn: LucideIcons.ZoomIn,
  ZoomOut: LucideIcons.ZoomOut,
};

export const getLucideIcon = (name?: string): LucideIcon | undefined => {
  if (!name || !availableIcons[name]) {
    return LucideIcons.Folder; // Default icon if name is not provided or not found
  }
  return availableIcons[name];
};

export const defaultCategoryIconName = 'Folder';
